name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger la pipeline sur les pushes vers la branche main
  pull_request:
    branches:
      - master  # Trigger également sur les pull requests vers la branche main

jobs:
  # Job pour les tests
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, mysql, pdo, pdo_mysql, intl
          coverage: none

      - name: Install dependencies via Composer
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel-ci-cd
          DB_USERNAME: smtAdmin
          DB_PASSWORD: Serigne@123
        run: php artisan migrate --seed

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox

  # Job pour le déploiement
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ne déploie que si les tests passent
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          echo "Déploiement en cours..."
          # Ajoute ici le script de déploiement, par exemple scp, rsync, ou déploiement via SSH
